image_width: 640
image_height: 480
camera_name: usb_cam_c920
camera_matrix:
  rows: 3
  cols: 3
  data: [639.109407, 0.000000, 337.483739, 0.000000, 641.461236, 224.754548, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.012303, -0.096321, -0.002877, 0.004612, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [635.628662, 0.000000, 339.576897, 0.000000, 0.000000, 640.420349, 223.328634, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
